### ISSUE TITLE
Use delegate methods for dynamic data sets

### ISSUE THREAD

**Issue by inb4ohnoes** [SergioChan/SCTrelloNavigation#1]
Instead of initializing everything with a data set, could you switch to delegate methods so that data sets can be dynamically changed and reloaded? Or if you believe that can be done properly now, could you provide what you think is best practice to do this?

**Comment by SergioChan** [comment]
Delegate would be better...haha...I've been just too busy yesterday for the 11.11... I will optimize it recently or you can push a PR to implement this? Thank you verrrry much for reading my project!

**Comment by inb4ohnoes** [comment]
Haha I've been doing a little 11.11 shopping myself so I understand... The main barring factor I have with using this in a little prototype project I'm thinking about doing is the fact that this doesn't really support dynamic data sets yet. If you don't do it first, I might take a look at adding it and submitting a pull request later...

**Comment by SergioChan** [comment]
@inb4ohnoes I will commit a new version later today or early tomorrow to close this issue, Dont worry

**Comment by inb4ohnoes** [comment]
Wow sounds good! I'll wait for your commit then. Hope got some good things for 双11!
